"use client";

import { X, Copy, Check } from "lucide-react";
import { useState } from "react";
import type { CreativeBrief, TikTokVideo } from "@/types";

interface BriefModalProps {
  brief: CreativeBrief;
  video: TikTokVideo;
  onClose: () => void;
}

export default function BriefModal({ brief, video, onClose }: BriefModalProps) {
  const [copied, setCopied] = useState(false);

  const briefText = `
CREATIVE BRIEF — ${brief.campaignName}
Generated by SoMe Scrub | Inspired by @${video.author.uniqueId}
${"─".repeat(50)}

OBJECTIVE
${brief.objective}

TARGET AUDIENCE
${brief.targetAudience}

KEY MESSAGE
${brief.keyMessage}

HOOK (First 3 Seconds)
${brief.hookIdea}

CONTENT FORMAT
${brief.contentFormat}

VISUAL STYLE
${brief.visualStyle}

CALL TO ACTION
${brief.callToAction}

INSPIRED BY
${brief.inspiredBy}

ADDITIONAL NOTES
${brief.additionalNotes}

${"─".repeat(50)}
Reference Video: ${video.webVideoUrl}
`.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(briefText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.9)" }}
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div
        className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl animate-slideUp"
        style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-10 p-1.5 rounded-lg transition-colors hover:bg-white/10"
          style={{ color: "var(--text-secondary)" }}
        >
          <X size={18} />
        </button>

        <div className="p-6 space-y-5">
          {/* Header */}
          <div className="space-y-1 pr-8">
            <div className="flex items-center gap-2">
              <span
                className="text-xs px-2 py-0.5 rounded-full font-medium"
                style={{ background: "rgba(0,212,160,0.15)", color: "var(--accent-teal)" }}
              >
                Creative Brief
              </span>
              <span className="text-xs" style={{ color: "var(--text-muted)" }}>
                Inspired by @{video.author.uniqueId}
              </span>
            </div>
            <h2 className="text-xl font-bold">{brief.campaignName}</h2>
          </div>

          {/* Brief fields */}
          <div className="space-y-3">
            <BriefField label="Objective" value={brief.objective} />
            <BriefField label="Target Audience" value={brief.targetAudience} />
            <BriefField label="Key Message" value={brief.keyMessage} />
            <BriefField
              label="Hook — First 3 Seconds"
              value={brief.hookIdea}
              highlight
            />
            <BriefField label="Content Format" value={brief.contentFormat} />
            <BriefField label="Visual Style" value={brief.visualStyle} />
            <BriefField label="Call to Action" value={brief.callToAction} />
            <BriefField label="Inspired By" value={brief.inspiredBy} />
            <BriefField label="Additional Notes" value={brief.additionalNotes} />
          </div>

          {/* Reference link */}
          <a
            href={video.webVideoUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs transition-colors hover:opacity-80 block"
            style={{ color: "var(--accent-pink)" }}
          >
            → View reference video on TikTok
          </a>

          {/* Copy button */}
          <button
            onClick={handleCopy}
            className="w-full flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm transition-colors hover:opacity-90"
            style={{ background: "var(--accent-teal)", color: "#000" }}
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? "Copied to clipboard!" : "Copy Brief to Clipboard"}
          </button>
        </div>
      </div>
    </div>
  );
}

function BriefField({
  label,
  value,
  highlight,
}: {
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <div
      className="rounded-lg p-3 space-y-1"
      style={{
        background: highlight ? "rgba(155,93,229,0.08)" : "var(--bg-input)",
        border: `1px solid ${highlight ? "rgba(155,93,229,0.3)" : "var(--border)"}`,
      }}
    >
      <p
        className="text-xs font-semibold uppercase tracking-wider"
        style={{ color: highlight ? "var(--accent-purple)" : "var(--accent-pink)" }}
      >
        {label}
      </p>
      <p className="text-sm leading-relaxed" style={{ color: "var(--text-primary)" }}>
        {value}
      </p>
    </div>
  );
}
